package com.igsl.model.mapping;

public enum JQLFunction {
	
}

/*
approved()
approver()
cascadeOption()
closedSprints()
componentsLeadByUser()
currentLogin()
currentUser()
earliestUnreleasedVersion()
endOfDay()
endOfMonth()
endOfWeek()
endOfYear()
issueHistory()
issuesWithRemoteLinksByGlobalId()
lastLogin()
latestReleasedVersion()
linkedIssues()
membersOf()
myApproval()
myPending()
now()
openSprints()
pending()
pendingBy()
projectsLeadByUser()
projectsWhereUserHasPermission()
projectsWhereUserHasRole()
releasedVersions()
standardIssueTypes()
startOfDay()
startOfMonth()
startOfWeek()
startOfYear()
subtaskIssueTypes()
unreleasedVersions()
votedIssues()
watchedIssues()
*/